name = "data-analytics-api"
main = "src/index.ts"
compatibility_date = "2025-10-04"

# --- Global Bindings ---
[[d1_databases]]
binding = "DB"
database_name = "analytics-db"
database_id = "6633e74a-4928-4bc2-96b9-e5702207919"

[ai]
binding = "AI"
remote = true  # Optional: silences remote resource warning

# --- Staging Environment ---
[env.staging]
name = "data-analytics-api-staging"
compatibility_date = "2025-10-04"

[env.staging.ai]
binding = "AI"
remote = true

[[env.staging.d1_databases]]
binding = "DB"
database_name = "analytics-api-staging"
database_id = "b47d8449-8491-496c-a70e-2d5531909ae1"

[env.staging.vars]
ENVIRONMENT = "staging"
PAYPAL_MODE = "sandbox" # ✅ Safe to commit (just tells which mode to use)

# --- Production Environment ---
[env.production]
name = "data-analytics-api-production"
compatibility_date = "2025-10-04"

[env.production.ai]
binding = "AI"
remote = true

[[env.production.d1_databases]]
binding = "DB"
database_name = "analytics-api-production"
database_id = "b0d30640-6935-48c7-..."  # ← Use full UUID from screenshot

[env.production.vars]
ENVIRONMENT = "production"
PAYPAL_MODE = "live"